# Generated by Django 2.2 on 2020-07-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginapi',
            table='customer_details',
        ),
    ]
